// Generated by https://quicktype.io

export interface ProductoDetalle {
  productos: Producto[];
}

export interface Producto {
  _id: string;
  tipo: string;
  nombre: string;
  descripcion: string;
  cantidad: number;
  precio: number;
  disponible: boolean;
  imagen: string;
  __v: number;
}
